language: objective-c
osx_image: xcode11.3

sudo: required

before_install:
  - gem install xcpretty --no-document --quiet

notifications:
  email:
    recipients:
      - niedongsen@yeah.net
    on_success: always
    on_failure: always

if: tag IS present

script:
- sh build.sh Release

deploy:
  provider: releases
  api_key: "${GH_TOKEN}"
  file: "./build/Release/BAXcodeCleaner.dmg"
  skip_cleanup: true
  overwrite: true
  on:
    tags: true
